# Generated by Django 4.0.1 on 2022-01-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
